/**
 * Column shapes every table repeats.
 *
 * `enaton` keeps these in a `mixins` module for the same reason: a table that
 * spells out its own key column will eventually spell one of them differently.
 * This schema had **three** id formats before that was true here — a UUID from a
 * repository, a config string from the environment, and `"service:cut"` built by
 * a seed script.
 */
import { char, text, timestamp } from "drizzle-orm/pg-core";
import { ulid } from "ulid";

/** ULIDs are 26 characters, always. */
export const ID_LENGTH = 26;

export const newId = (): string => ulid();

/**
 * The standard primary key: a ULID, generated client-side. `enaton`'s `pk()`.
 *
 * **ULID over UUIDv4** because it sorts lexicographically by creation time. A v4
 * uuid scatters inserts across the whole B-tree, splitting pages and dirtying
 * cache lines all over the index; a ULID appends, so a table like `entries`
 * writes to the same few pages. That is a real difference on the small box
 * doc 14 targets, and it costs nothing.
 *
 * **`char(26)` over `text`** because the width documents the format and rejects
 * a wrong-length id at the column rather than three layers up. Postgres stores
 * both as varlena, so this is about the constraint, not the bytes.
 *
 * **Generated by default** so no caller invents one — the part that had actually
 * gone wrong, since id generation was scattered across a repository and a script.
 */
export const pk = () =>
  char({ length: ID_LENGTH })
    .primaryKey()
    .$defaultFn(() => newId());

/** A column pointing at another table's `pk()`. Same width, same constraint. */
export const fk = () => char({ length: ID_LENGTH });

/**
 * An id supplied by configuration rather than generated.
 *
 * `organizations.id` and `sites.id` come from `ORG_ID` and `SITE_ID`, which
 * default to `"default"` on a single-site install. Forcing a ULID there would
 * mean a self-hoster putting a 26-character opaque string in their `.env` for no
 * gain — this is the one place a human names a row, and it should stay legible.
 */
export const configuredId = () => text();

export const createdAt = () => timestamp({ withTimezone: true }).notNull().defaultNow();
