/**
 * Column shapes every table repeats.
 *
 * Kept in one module because a table that spells out its own key column will
 * eventually spell one of them differently.
 * This schema had **three** id formats before that was true here — a UUID from a
 * repository, a config string from the environment, and `"service:cut"` built by
 * a seed script.
 */
import { sql } from "drizzle-orm";
import { text, timestamp, uuid } from "drizzle-orm/pg-core";
import { uuidv7 } from "uuidv7";

/**
 * The standard primary key: a UUIDv7, generated by Postgres.
 *
 * **v7 over v4** because it embeds a millisecond timestamp in its high bits and
 * therefore sorts by creation time. A v4 scatters inserts across the whole
 * B-tree, splitting pages and dirtying cache lines all over the index; a v7
 * appends, so a table like `entries` writes to the same few pages. That is a
 * real difference on the small box doc 14 targets.
 *
 * **`uuid` over a ULID in `char(26)`**, which this was first: 16 bytes against
 * 30 measured, a native type every driver and tool already understands, and no
 * npm dependency. A ULID is a convention only this codebase knows; a uuid column
 * is not.
 *
 * **Generated twice over**, which is better than either half alone:
 *
 *   - `$defaultFn` (client-side, the `uuidv7` package) so a Drizzle insert knows
 *     its id without a `RETURNING` round-trip — which is what lets a
 *     transaction build a graph of related rows before writing any of them.
 *   - `default uuidv7()` (server-side, native in Postgres 18) as the safety net
 *     for anything that bypasses Drizzle: raw SQL, a seed, someone in `psql`.
 *
 * Either alone leaves a gap. Together, nothing can insert a row without a
 * time-ordered id — which is the part that had actually gone wrong before, when
 * generation was scattered across a repository and a script.
 */
export const pk = () =>
  uuid()
    .primaryKey()
    .default(sql`uuidv7()`)
    .$defaultFn(() => uuidv7());

/** A column pointing at another table's `pk()`. Same type, same constraint. */
export const fk = () => uuid();

/**
 * An id supplied by configuration rather than generated.
 *
 * `organizations.id` and `sites.id` come from `ORG_ID` and `SITE_ID`, which
 * default to `"default"` on a single-site install. Forcing a uuid there would
 * mean a self-hoster putting an opaque string in their `.env` for no gain —
 * this is the one place a human names a row, and it should stay legible.
 */
export const configuredId = () => text();

export const createdAt = () => timestamp({ withTimezone: true }).notNull().defaultNow();
